const resList = [{
    type: "restaurant",
    data: {
        type: "F",
        id: "334475",
        name: "KFC",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002510.jpg?ver=60.2",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "$400 For Two",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "3.8",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334476",
        name: "Healthy Bites",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/4dfbe240cf1a2be01e6f2805c75c4279",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "$400 For Two",
        deliveryTime: 38,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "4.0",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334478",
        name: "Maghana Hotel",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/glepanv4xjfnhsbieam1",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "$400 For Two",
        deliveryTime: 40,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "4.2",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334479",
        name: "KFC",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002510.jpg?ver=60.2",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "$400 For Two",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "3.8",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334471",
        name: "Healthy Bites",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/4dfbe240cf1a2be01e6f2805c75c4279",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "$400 For Two",
        deliveryTime: 38,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "4.0",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334472",
        name: "Maghana Hotel",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/glepanv4xjfnhsbieam1",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "$400 For Two",
        deliveryTime: 40,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "4.2",
        totalRating: 500,
        new: false,
    },
    subtype: false,
}, {
    type: "restaurant",
    data: {
        type: "F",
        id: "334470",
        name: "Maghana Hotel",
        uuid: "eaed0e3b-7c0e-4367-8f59-f41d309fb93a",
        city: "1",
        area: "BTM Layout",
        totalRatingString: "500+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/glepanv4xjfnhsbieam1",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "$400 For Two",
        deliveryTime: 40,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3.5,
        slugs: {
            restaurent: "kfc-btm-layout-btm",
            city: "bangalore",
        },
        cityState: "1",
        address: "KFC restaurent, 942,sv Tower, 16th Main, BTM 2nd Stage, 560076",
        locality: "2nd Stage",
        presentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "FREE DELIVERY",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
            header: "",
            shortDescriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT", 
                },
            ],
            descriptionList: [
                {
                    meta: "FREE DELIVERY",
                    discountType: "FREE_DELIVERY",
                    operationType: "RESTAURANT",
                },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
        },
        ribbon: [
            {
                type: "PROMOTED",
            },
        ],
        chain: [],
        freeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
        },
        availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMassage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyVendor: "",
        adTrackingId: "cid=6109309~p=1~eid=00000186-a341-249f-05e6-09c500910178",
        badges: {
            imageBased: [],
            textBased: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
            restaurentId: "334475",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 3.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentailService: false,
            iconType: "Empty",
        },
        promoted: true,
        avgRating: "4.2",
        totalRating: 500,
        new: false,
    },
    subtype: false,
} ]

export default resList;